[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200


[rpc_endpoints]
viction_devnet = "https://rpc.viction-qcnet.tforce.dev/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
